version: "3.8"
services:
  frontend-prod:
    build: ./frontend
    container_name: frontend-prod
    ports:
      - '3000:3000'
    volumes:
      - /app
  backend-prod:
    build: ./backend
    container_name: backend-prod
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    volumes:
      - /app
